apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crud-api
    tags.datadoghq.com/env: "staging"
    tags.datadoghq.com/service: "crud-api"
    tags.datadoghq.com/version: "a8e3cv"
  name: crud-api
  namespace: keda-datadog-demo
spec:
  selector:
    matchLabels:
      app: crud-api
  template:
    metadata:
      labels:
        app: crud-api
        tags.datadoghq.com/env: "staging"
        tags.datadoghq.com/service: "crud-api"
        tags.datadoghq.com/version: "a8e3cv"
    spec:
      containers:
      - image: waiyanwinhtain/datadog-node-apm:latest
        name: datadog-node-apm
        ports:
        - containerPort: 3000
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/env']
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']
          - name: DD_LOGS_INJECTION
            value: "true"
