apiVersion: v1
kind: Service
metadata:
  name: demo-keda-svc
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "3000"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: demo-keda

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-keda
spec:
  selector:
    matchLabels:
      app: demo-keda
  template:
    metadata:
      labels:
        app: demo-keda
    spec:
      containers:
      - name: demo-keda
        image: waiyanwinhtain/nodejs-prom-counter:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 0.4
            memory: 700Mi
          requests:
            cpu: 0.2
            memory: 400Mi
