apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demo-keda-scaledobject
  namespace: demo-app
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          demo-keda
  pollingInterval: 10     # Optional. Default: 30 seconds
  cooldownPeriod: 100     # Optional. Default: 300 seconds
  minReplicaCount: 1      # Optional. Default: 0
  maxReplicaCount: 10      # Optional. Default: 100
  fallback:               # Optional. Section to specify fallback options
    failureThreshold: 3   # Mandatory if fallback section is included
    replicas: 1
  advanced: # Optional. Section to specify advanced options
    horizontalPodAutoscalerConfig: # Optional. Section to specify HPA related options
      behavior: # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
          - type: Percent
            value: 50
            periodSeconds: 15
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local:80/
        query: sum(rate(hello_world_requests{service="demo-keda-svc"}[1m])) # Note: query must return a vector/scalar single element response
        threshold: '50'
        # Optional fields:
        ignoreNullValues: "true" # Default is `true`, which means ignoring the empty value list from Prometheus. Set to `false` the scaler will return error when Prometheus target is lost
